## Import Libraries

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import seaborn as sns
sns.set()

## Import Data

In [59]:
file_path = "C:/Users/Souhar/OneDrive/Desktop/Christ programming/MDS372(Machine Learning)/Final Project/Dataset/Merged_data.csv"  # Change to your actual file path
df = pd.read_csv(file_path)

In [60]:
df.head()

,Slno,Area,Year,Rural population,Urban population,Urbanization Rate,"Abaca, manila hemp, raw","Agave fibres, raw, n.e.c.","Almonds, in shell","Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",...,Cropland,Farm buildings and Farmyards,Perm. meadows & pastures - Cultivated,Perm. meadows & pastures - Nat. growing,Permanent crops,Permanent meadows and pastures,Temporary crops,Temporary fallow,Temporary meadows and pastures,Nutrient balance
0,0,Afghanistan,2020,28150.604,9904.337,0.351834,0.0,0.0,39307.0,17965.90,...,8051.000,0.00,0.0,30262.0,222.000,30262.0,3834.0,3995.0,0.0,1.575433
1,1,Afghanistan,2021,28674.023,10239.684,0.357107,0.0,0.0,64256.0,17876.49,...,8051.000,0.00,0.0,30262.0,222.000,30262.0,3834.0,3995.0,0.0,1.844533
2,2,Afghanistan,2022,29191.512,10587.583,0.362694,0.0,0.0,63515.0,17883.38,...,8051.000,0.00,0.0,30262.0,222.000,30262.0,3834.0,3995.0,0.0,2.193200
3,3,Albania,2020,1114.672,1827.362,1.639372,0.0,0.0,0.0,0.00,...,687.555,1.79,0.0,0.0,87.955,478.0,196.6,178.0,225.0,42.048833
4,4,Albania,2021,1090.487,1854.317,1.700449,0.0,0.0,0.0,0.00,...,687.530,1.87,0.0,0.0,87.630,448.8,200.9,179.3,219.7,37.402333

In [61]:
df.describe()

c:\Users\Souhar\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Slno,Year,Rural population,Urban population,Urbanization Rate,"Abaca, manila hemp, raw","Agave fibres, raw, n.e.c.","Almonds, in shell","Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",Apples,...,Cropland,Farm buildings and Farmyards,Perm. meadows & pastures - Cultivated,Perm. meadows & pastures - Nat. growing,Permanent crops,Permanent meadows and pastures,Temporary crops,Temporary fallow,Temporary meadows and pastures,Nutrient balance
count,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,5.400000e+02,5.400000e+02,5.400000e+02,...,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000,540.000000
mean,269.500000,2020.994444,18402.112402,24083.508439,inf,602.973611,203.200167,2.162174e+04,1.470222e+04,5.121910e+05,...,8544.949956,92.042700,455.456236,5591.905631,1014.595528,17256.686618,5892.861232,881.122894,757.030709,35.335934
std,156.028843,0.818369,79506.102275,81270.533080,NaN,5813.186618,1332.501162,1.645362e+05,1.377902e+05,3.465755e+06,...,22743.179206,974.764757,1880.102170,30599.522500,2973.830678,49429.525041,16829.978521,2645.417524,3516.515644,80.348701
min,0.000000,2020.000000,0.000000,13.223000,0.154005,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,...,0.660000,0.000000,0.000000,0.000000,0.000000,0.000000,0.148500,0.000000,0.000000,-247.725000
25%,134.750000,2020.000000,643.847500,1508.485250,0.750042,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,...,191.400000,0.000000,0.000000,0.000000,23.937500,190.000000,107.442075,8.389200,0.218900,3.816167
50%,269.500000,2021.000000,2625.781000,5089.279500,1.637758,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,...,1749.000000,0.000000,0.000000,0.000000,132.000000,1350.000000,1004.456800,90.250000,35.839450,17.957383
75%,404.250000,2022.000000,11378.744250,16028.818000,3.654137,0.000000,0.000000,0.000000e+00,0.000000e+00,1.558825e+05,...,6091.111550,0.000000,0.000000,3.400000,600.000000,11000.000000,4108.476925,449.481075,336.477700,39.594933
max,539.000000,2022.000000,905110.427000,910080.750000,inf,68702.460000,14920.430000,2.345070e+06,1.876972e+06,4.757180e+07,...,168047.948000,13232.128700,20867.100000,371965.900000,27447.713000,392833.000000,141632.612500,25011.725000,44453.032000,851.754167

## Data Preprocessing

### <b>Dropping Slno

In [62]:
df=df.drop("Slno",axis=1)

### <b>Imputing inf values in "Urbanization Rate"

In [63]:
df["Urbanization Rate"].max()

inf

In [64]:
df["Urbanization Rate"].replace([np.inf, -np.inf], np.nan, inplace=True)

C:\Users\Souhar\AppData\Local\Temp\ipykernel_37616\1678373089.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Urbanization Rate"].replace([np.inf, -np.inf], np.nan, inplace=True)

In [65]:
df["Urbanization Rate"]=df["Urbanization Rate"].fillna(df["Urbanization Rate"].mean())

In [66]:
df["Urbanization Rate"].max()

145.5944081

In [67]:
df=df.drop(["Rural population","Urban population"],axis=1)

Dropping urban and rural polulation columns as they are directly related to urbanization rate to prevent data leakage

### <b>Missing value check

In [68]:
df.isna().sum()[df.isna().sum()>0]

Series([], dtype: int64)

No missing values

### <b>Drop "Area"

In [69]:
df1=df.copy()

In [70]:
countries=df1["Area"]

In [71]:
df1=df1.drop("Area",axis=1)

### <b>Multicollinearity

<b>Checking for high correlation features

In [72]:

corr_matrix = df1.corr()

high_corr_threshold = 0.7

high_corr_pairs = (
    corr_matrix.where(abs(corr_matrix) > high_corr_threshold) 
    .stack()  
    .reset_index()
)

high_corr_pairs.columns = ["Feature 1", "Feature 2", "Correlation"]

# Remove duplicate pairs (since correlation is symmetric)
high_corr_pairs = high_corr_pairs[high_corr_pairs["Feature 1"] != high_corr_pairs["Feature 2"]]

high_corr_pairs.sort_values(by="Correlation", ascending=False)

,Feature 1,Feature 2,Correlation
2316,"Meat of geese, fresh or chilled",Mushrooms and truffles,0.999789
2746,Mushrooms and truffles,"Meat of geese, fresh or chilled",0.999789
5147,Agriculture,Agricultural land,0.999767
5129,Agricultural land,Agriculture,0.999767
4387,Spinach,Tallowtree seeds,0.999531
...,...,...,...
2428,"Meat of mules, fresh or chilled","Horse meat, fresh or chilled",0.700475
922,"Cinnamon and cinnamon-tree flowers, raw","Tangerines, mandarins, clementines",0.700320
4614,"Tangerines, mandarins, clementines","Cinnamon and cinnamon-tree flowers, raw",0.700320
4230,"Sheep fat, unrendered","Meat of rabbits and hares, fresh or chilled",0.700198
2587,"Meat of rabbits and hares, fresh or chilled","Sheep fat, unrendered",0.700198

Several feataures have high inter correlation that might result in multicollinearity. We drop one of all such features

### <b>Dropping highly correlated features

In [73]:
# Upper triangle of the correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

features_to_drop = [column for column in upper.columns if any(upper[column] > 0.7)]

# Drop the identified features
df1 = df1.drop(columns=features_to_drop)

print(f"Removed {len(features_to_drop)} highly correlated features.")

Removed 164 highly correlated features.

### <b>Checking for high VIF

In [74]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Drop columns with all NaN or constant values (to avoid errors)
df1 = df1.dropna(axis=1, how='all')  
df1 = df1.loc[:, (df1 != df1.iloc[0]).any()]  

# Drop rows with NaN values (optional, but ensures no errors in VIF calculation)
df1 = df1.dropna()

# Compute VIF for each feature
vif_data = pd.DataFrame()
vif_data["Feature"] = df1.columns
vif_data["VIF"] = [variance_inflation_factor(df1.values, i) for i in range(df1.shape[1])]

# Sort by VIF in descending order
vif_data = vif_data.sort_values(by="VIF", ascending=False)

# Filter only features with VIF > 5
vif_high = vif_data[vif_data["VIF"] > 10]

# Display high VIF features
print(vif_high)
print()
print("No. of high VIF columns:", vif_high.shape[0])

                      Feature        VIF
0                        Year  83.163849
22         Coconuts, in shell  20.520916
30                  Hop cones  16.657096
54                    Sorghum  15.102168
4           Almonds, in shell  12.879324
20  Cloves (whole stems), raw  12.802772
52                        Rye  12.229651

No. of high VIF columns: 7

In [75]:
features_to_exclude = vif_high[vif_high["Feature"] != "Year"]["Feature"].tolist()
features_to_exclude

['Coconuts, in shell',
 'Hop cones',
 'Sorghum',
 'Almonds, in shell',
 'Cloves (whole stems), raw',
 'Rye']

In [76]:
df1=df1.drop(columns=features_to_exclude)

In [77]:
df1

,Year,Urbanization Rate,"Abaca, manila hemp, raw","Agave fibres, raw, n.e.c.","Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",Apples,Apricots,Artichokes,Avocados,"Bambara beans, dry",...,Sesame seed,Sour cherries,"Vanilla, raw",Yautia,Food Price Index,Average dietary energy requirement (kcal/cap/day),Percentage of children under 5 years affected by wasting (percent),Prevalence of severe food insecurity in the total population (percent) (3-year average),Prevalence of undernourishment (percent) (3-year average),Nutrient balance
0,2020,0.351834,0.0,0.0,17965.90,270857.0,131788.00,0.00,0.0,0.00,...,41855.0,0.00,0.00,0.0,127.61,2134,0.0,22.6,27.7,1.575433
1,2021,0.357107,0.0,0.0,17876.49,321672.0,207490.00,0.00,0.0,0.00,...,19000.0,0.00,0.00,0.0,134.66,2138,0.0,28.4,29.4,1.844533
2,2022,0.362694,0.0,0.0,17883.38,318402.0,170508.00,0.00,0.0,0.00,...,41871.0,0.00,0.00,0.0,160.10,2140,3.6,30.6,30.4,2.193200
3,2020,1.639372,0.0,0.0,0.00,102167.0,5143.00,0.00,0.0,0.00,...,0.0,17848.67,0.00,0.0,117.50,2488,0.0,7.7,4.4,42.048833
4,2021,1.700449,0.0,0.0,0.00,111247.2,5056.70,0.00,0.0,0.00,...,0.0,17857.77,0.00,0.0,122.09,2489,0.0,7.5,4.3,37.402333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2021,0.824554,0.0,0.0,0.00,0.0,0.00,0.00,0.0,6757.73,...,0.0,0.00,0.00,0.0,225.87,2204,0.0,0.0,34.4,16.287567
536,2022,0.843684,0.0,0.0,0.00,0.0,0.00,0.00,0.0,5828.86,...,0.0,0.00,0.00,0.0,255.50,2209,0.0,0.0,35.4,17.131733
537,2020,0.475831,0.0,0.0,84.18,4347.0,45.03,303.88,84091.0,23832.00,...,5037.0,0.00,9.93,0.0,3644.44,2245,0.0,31.3,39.5,3.421333
538,2021,0.477176,0.0,0.0,84.20,4032.0,44.93,303.99,93280.0,37156.00,...,11802.0,0.00,9.92,0.0,7500.21,2251,0.0,28.6,38.9,4.174700
539,2022,0.479183,0.0,0.0,83.52,4708.0,45.15,303.81,96348.0,45539.02,...,8000.0,0.00,9.91,0.0,18748.05,2257,0.0,26.0,38.1,1.714267

## <b>Feature Scaling(Standardization)

In [78]:
df2=df1.copy()

In [79]:
df2

,Year,Urbanization Rate,"Abaca, manila hemp, raw","Agave fibres, raw, n.e.c.","Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw",Apples,Apricots,Artichokes,Avocados,"Bambara beans, dry",...,Sesame seed,Sour cherries,"Vanilla, raw",Yautia,Food Price Index,Average dietary energy requirement (kcal/cap/day),Percentage of children under 5 years affected by wasting (percent),Prevalence of severe food insecurity in the total population (percent) (3-year average),Prevalence of undernourishment (percent) (3-year average),Nutrient balance
0,2020,0.351834,0.0,0.0,17965.90,270857.0,131788.00,0.00,0.0,0.00,...,41855.0,0.00,0.00,0.0,127.61,2134,0.0,22.6,27.7,1.575433
1,2021,0.357107,0.0,0.0,17876.49,321672.0,207490.00,0.00,0.0,0.00,...,19000.0,0.00,0.00,0.0,134.66,2138,0.0,28.4,29.4,1.844533
2,2022,0.362694,0.0,0.0,17883.38,318402.0,170508.00,0.00,0.0,0.00,...,41871.0,0.00,0.00,0.0,160.10,2140,3.6,30.6,30.4,2.193200
3,2020,1.639372,0.0,0.0,0.00,102167.0,5143.00,0.00,0.0,0.00,...,0.0,17848.67,0.00,0.0,117.50,2488,0.0,7.7,4.4,42.048833
4,2021,1.700449,0.0,0.0,0.00,111247.2,5056.70,0.00,0.0,0.00,...,0.0,17857.77,0.00,0.0,122.09,2489,0.0,7.5,4.3,37.402333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2021,0.824554,0.0,0.0,0.00,0.0,0.00,0.00,0.0,6757.73,...,0.0,0.00,0.00,0.0,225.87,2204,0.0,0.0,34.4,16.287567
536,2022,0.843684,0.0,0.0,0.00,0.0,0.00,0.00,0.0,5828.86,...,0.0,0.00,0.00,0.0,255.50,2209,0.0,0.0,35.4,17.131733
537,2020,0.475831,0.0,0.0,84.18,4347.0,45.03,303.88,84091.0,23832.00,...,5037.0,0.00,9.93,0.0,3644.44,2245,0.0,31.3,39.5,3.421333
538,2021,0.477176,0.0,0.0,84.20,4032.0,44.93,303.99,93280.0,37156.00,...,11802.0,0.00,9.92,0.0,7500.21,2251,0.0,28.6,38.9,4.174700
539,2022,0.479183,0.0,0.0,83.52,4708.0,45.15,303.81,96348.0,45539.02,...,8000.0,0.00,9.91,0.0,18748.05,2257,0.0,26.0,38.1,1.714267

In [80]:
from sklearn.preprocessing import MinMaxScaler

# Store the "Year" column separately before scaling
year_column = df2["Year"].values  

# Scale all other features
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(df2.drop(columns=["Year"]))

# Convert back to DataFrame
df2 = pd.DataFrame(scaled_features, columns=df2.columns[1:])  # Only feature columns

# Add back the "Year" column
df2.insert(0, "Year", year_column)  

print(df2.head())  # Check scaled data

   Year  Urbanization Rate  Abaca, manila hemp, raw  \
0  2020           0.001360                      0.0
1  2021           0.001396                      0.0
2  2022           0.001435                      0.0
3  2020           0.010213                      0.0
4  2021           0.010633                      0.0

   Agave fibres, raw, n.e.c.  \
0                        0.0
1                        0.0
2                        0.0
3                        0.0
4                        0.0

   Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw  \
0                                           0.009572
1                                           0.009524
2                                           0.009528
3                                           0.000000
4                                           0.000000

     Apples  Apricots  Artichokes  Avocados  Bambara beans, dry  ...  \
0  0.005694  0.158133         0.0       0.0                 0.0  ...
1  0.006762  0.248969         0.0       0.0                 0.0  ...
2  0.006693  0.204594         0.0       0.0                 0.0  ...
3  0.002148  0.006171         0.0       0.0                 0.0  ...
4  0.002339  0.006068         0.0       0.0                 0.0  ...

   Sesame seed  Sour cherries  Vanilla, raw  Yautia  Food Price Index  \
0     0.023542       0.000000           0.0     0.0      8.087356e-11
1     0.010687       0.000000           0.0     0.0      9.708046e-11
2     0.023551       0.000000           0.0     0.0      1.555632e-10
3     0.000000       0.060056           0.0     0.0      5.763218e-11
4     0.000000       0.060087           0.0     0.0      6.818391e-11

   Average dietary energy requirement (kcal/cap/day)  \
0                                           0.769009
1                                           0.770450
2                                           0.771171
3                                           0.896577
4                                           0.896937

   Percentage of children under 5 years affected by wasting (percent)  \
0                                           0.000000
1                                           0.000000
2                                           0.192513
3                                           0.000000
4                                           0.000000

   Prevalence of severe food insecurity in the total population (percent) (3-year average)  \
0                                           0.357595
1                                           0.449367
2                                           0.484177
3                                           0.121835
4                                           0.118671

   Prevalence of undernourishment (percent) (3-year average)  Nutrient balance
0                                           0.539961                  0.226744
1                                           0.573099                  0.226989
2                                           0.592593                  0.227306
3                                           0.085770                  0.263556
4                                           0.083821                  0.259329

[5 rows x 58 columns]

## <b>Train test split

In [81]:
# Define the features (X) and target (y)
X = df2.drop(columns=["Prevalence of severe food insecurity in the total population (percent) (3-year average)"])
y = df2["Prevalence of severe food insecurity in the total population (percent) (3-year average)"]

In [82]:
# Split the data into training and test sets (80% train, 20% test)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## <b>XG Boost

In [83]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

xgb_model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

print(f"XGBoost - RMSE: {rmse_xgb}")
print(f"XGBoost - RÂ²: {r2_xgb}")

XGBoost - RMSE: 0.08260928390021936
XGBoost - RÂ²: 0.7973521686985227

In [85]:
predict_data=X.copy()
predict_data["Country"]=countries

In [87]:
predict_data.to_csv("Prediction Data")

In [84]:
import joblib

# Save the trained model
joblib.dump(xgb_model, "model.pkl")

['model.pkl']